// ============================================================
// Open-chat mode — Types
// ============================================================

import type { ModelConfig } from '@agora/shared'

export interface OpenChatAgentConfig {
  /** Stable agent id (pre-generated by room creator, persisted in rooms.agents snapshot). */
  readonly id: string
  readonly name: string
  /** Short persona description (shown on agent cards, not used as the system prompt). */
  readonly persona: string
  /**
   * Full system prompt the room will give this agent at reply time.
   * Caller is responsible for composing it — including language directive,
   * topic context, and (for leader) the dispatch-discipline block.
   */
  readonly systemPrompt: string
  readonly model: ModelConfig
}

export interface OpenChatConfig {
  readonly agents: readonly OpenChatAgentConfig[]
  /** User-provided opening question/topic. Shown in UI, may be referenced by system prompts. */
  readonly topic: string
  /** Total laps through the roster. Default 3. Clamped 1..10. */
  readonly rounds?: number
  /** If set, this agent speaks first (and first in every subsequent lap). Must be in agents[]. */
  readonly leaderAgentId?: string | null
  /** Stable room id (required — caller generates upfront and persists). */
  readonly roomId: string
}

export interface OpenChatGameStateSnapshot {
  readonly topic: string
  readonly turnsCompleted: number
  readonly totalTurns: number
}
