// ============================================================
// Phase 6 — Build seed-template migration
// ============================================================
//
// Reads every `*.json` under `scripts/seed/templates/` (except
// `_README.md`), assigns deterministic UUIDs via
// `@agora/shared`'s `seededUuid`, and emits:
//
//   packages/db/drizzle/0004_seed_templates.sql
//
// Also appends an entry to `drizzle/meta/_journal.json` so the
// migrator picks it up. Re-running the script is idempotent: the
// SQL is INSERT ... ON CONFLICT DO NOTHING, and the journal entry
// is deduplicated by tag.
//
// Run from repo root:
//   pnpm --filter @agora/db tsx scripts/build-template-sql.ts

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { seededUuid } from '@agora/shared'

// ── Types ──────────────────────────────────────────────────

interface TemplateAgentJson {
  slug: string
  name: string
  avatarSeed: string
  modelProvider: 'anthropic' | 'openai' | 'google' | 'deepseek'
  modelId: string
  style: { temperature?: number; maxTokens?: number; language?: 'zh' | 'en'; [k: string]: unknown }
  persona: string
  systemPrompt?: string | null
}

interface TemplateJson {
  slug: string
  name: string
  description: string
  avatarSeed: string
  defaultModeId: 'open-chat' | 'roundtable' | 'werewolf'
  leaderAgentSlug: string | null
  agents: TemplateAgentJson[]
}

// ── Paths ──────────────────────────────────────────────────

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '../../..')
const templatesDir = path.join(repoRoot, 'scripts/seed/templates')
const drizzleDir = path.join(repoRoot, 'packages/db/drizzle')
const sqlOut = path.join(drizzleDir, '0004_seed_templates.sql')
const journalPath = path.join(drizzleDir, 'meta/_journal.json')

// ── Load + validate ────────────────────────────────────────

function loadTemplates(): TemplateJson[] {
  const entries = fs
    .readdirSync(templatesDir)
    .filter((f) => f.endsWith('.json'))
    .sort() // stable order → stable SQL
  const out: TemplateJson[] = []
  for (const file of entries) {
    const raw = fs.readFileSync(path.join(templatesDir, file), 'utf8')
    let parsed: TemplateJson
    try {
      parsed = JSON.parse(raw) as TemplateJson
    } catch (err) {
      throw new Error(`Failed to parse ${file}: ${(err as Error).message}`)
    }
    validate(parsed, file)
    out.push(parsed)
  }
  return out
}

function validate(t: TemplateJson, source: string): void {
  if (!t.slug || typeof t.slug !== 'string') throw new Error(`${source}: missing slug`)
  if (!t.name || typeof t.name !== 'string') throw new Error(`${source}: missing name`)
  if (!Array.isArray(t.agents) || t.agents.length === 0) {
    throw new Error(`${source}: agents must be non-empty array`)
  }
  if (t.leaderAgentSlug !== null) {
    if (!t.agents.find((a) => a.slug === t.leaderAgentSlug)) {
      throw new Error(`${source}: leaderAgentSlug "${t.leaderAgentSlug}" not in agents`)
    }
  }
  const slugs = new Set<string>()
  for (const a of t.agents) {
    if (slugs.has(a.slug)) throw new Error(`${source}: duplicate agent slug "${a.slug}"`)
    slugs.add(a.slug)
    if (!a.persona || a.persona.length < 100) {
      throw new Error(`${source}: agent "${a.slug}" persona too short (<100 chars)`)
    }
    if (a.persona.length > 4000) {
      throw new Error(`${source}: agent "${a.slug}" persona too long (>4000 chars)`)
    }
  }
}

// ── UUIDs ──────────────────────────────────────────────────

function teamId(templateSlug: string): string {
  return seededUuid('agora-template:team', templateSlug)
}
function agentId(templateSlug: string, agentSlug: string): string {
  return seededUuid('agora-template:agent', `${templateSlug}:${agentSlug}`)
}

// ── SQL emit ───────────────────────────────────────────────

function escSql(s: string): string {
  // Safe only for our own controlled content. No user input here.
  return s.replaceAll("'", "''")
}

function jsonLiteral(obj: unknown): string {
  return `'${escSql(JSON.stringify(obj))}'::jsonb`
}

function buildSql(templates: TemplateJson[]): string {
  const lines: string[] = []

  lines.push('-- ============================================================')
  lines.push('-- Phase 6 seed templates — generated by scripts/build-template-sql.ts')
  lines.push('-- Re-running is safe: all inserts use ON CONFLICT DO NOTHING.')
  lines.push('-- Do not edit by hand; regenerate from scripts/seed/templates/*.json.')
  lines.push('-- ============================================================')
  lines.push('')

  // Pass 1 — agents
  lines.push('-- Agents')
  for (const t of templates) {
    for (const a of t.agents) {
      const id = agentId(t.slug, a.slug)
      const sysPrompt = a.systemPrompt ? `'${escSql(a.systemPrompt)}'` : 'NULL'
      lines.push(
        `INSERT INTO "agents" ("id","created_by","name","persona","system_prompt","model_provider","model_id","style","avatar_seed","is_template") VALUES (`,
      )
      lines.push(`  '${id}',`)
      lines.push(`  NULL,`)
      lines.push(`  '${escSql(a.name)}',`)
      lines.push(`  '${escSql(a.persona)}',`)
      lines.push(`  ${sysPrompt},`)
      lines.push(`  '${escSql(a.modelProvider)}',`)
      lines.push(`  '${escSql(a.modelId)}',`)
      lines.push(`  ${jsonLiteral(a.style ?? {})},`)
      lines.push(`  '${escSql(a.avatarSeed)}',`)
      lines.push(`  true`)
      lines.push(`) ON CONFLICT ("id") DO NOTHING;`)
      lines.push('')
    }
  }

  // Pass 2 — teams (leader FK resolves to agent id above)
  lines.push('-- Teams')
  for (const t of templates) {
    const tid = teamId(t.slug)
    const leaderId = t.leaderAgentSlug ? `'${agentId(t.slug, t.leaderAgentSlug)}'` : 'NULL'
    lines.push(
      `INSERT INTO "teams" ("id","created_by","name","description","avatar_seed","leader_agent_id","default_mode_id","is_template") VALUES (`,
    )
    lines.push(`  '${tid}',`)
    lines.push(`  NULL,`)
    lines.push(`  '${escSql(t.name)}',`)
    lines.push(`  '${escSql(t.description)}',`)
    lines.push(`  '${escSql(t.avatarSeed)}',`)
    lines.push(`  ${leaderId},`)
    lines.push(`  '${escSql(t.defaultModeId)}',`)
    lines.push(`  true`)
    lines.push(`) ON CONFLICT ("id") DO NOTHING;`)
    lines.push('')
  }

  // Pass 3 — team_members
  lines.push('-- Team members')
  for (const t of templates) {
    const tid = teamId(t.slug)
    for (let i = 0; i < t.agents.length; i++) {
      const a = t.agents[i]!
      const aid = agentId(t.slug, a.slug)
      lines.push(
        `INSERT INTO "team_members" ("team_id","agent_id","position") VALUES ('${tid}','${aid}',${i}) ON CONFLICT ("team_id","agent_id") DO NOTHING;`,
      )
    }
    lines.push('')
  }

  return lines.join('\n')
}

// ── Journal ────────────────────────────────────────────────

interface Journal {
  version: string
  dialect: string
  entries: { idx: number; version: string; when: number; tag: string; breakpoints: boolean }[]
}

function updateJournal(tag: string): void {
  const journal = JSON.parse(fs.readFileSync(journalPath, 'utf8')) as Journal
  const existing = journal.entries.find((e) => e.tag === tag)
  if (existing) {
    console.log(`[build-template-sql] journal entry already present for ${tag}`)
    return
  }
  const nextIdx = journal.entries.length
  journal.entries.push({
    idx: nextIdx,
    version: journal.entries[0]?.version ?? '7',
    when: Date.now(),
    tag,
    breakpoints: true,
  })
  fs.writeFileSync(journalPath, JSON.stringify(journal, null, 2) + '\n')
  console.log(`[build-template-sql] added journal entry ${nextIdx} for ${tag}`)
}

// ── Main ───────────────────────────────────────────────────

function main(): void {
  const templates = loadTemplates()
  if (templates.length === 0) {
    console.error(`No templates found in ${templatesDir}`)
    process.exit(1)
  }
  const totalAgents = templates.reduce((sum, t) => sum + t.agents.length, 0)
  const totalPersonaChars = templates.reduce(
    (sum, t) => sum + t.agents.reduce((s, a) => s + a.persona.length, 0),
    0,
  )
  console.log(
    `[build-template-sql] ${templates.length} templates, ${totalAgents} agents, ${totalPersonaChars} persona chars`,
  )

  const sql = buildSql(templates)
  fs.writeFileSync(sqlOut, sql)
  console.log(`[build-template-sql] wrote ${sqlOut}`)

  updateJournal('0004_seed_templates')
}

main()
